"""Backend regression tests for Factory CMMS Enterprise.

Focus of THIS iteration:
- Shift removal validation (no `shift` field in breakdowns/work_orders responses)
- Bulk runtime CSV import (dry-run, commit, template) — happy + edge cases
- Department cascading (dept -> lines scope), department KPI endpoint

Uses REACT_APP_BACKEND_URL from environment. Run:
    pytest /app/backend/tests/backend_test.py -v --junitxml=/app/test_reports/pytest/pytest_results.xml
"""
import io
import os
import pytest
import requests


def _multipart_post(session: requests.Session, url: str, files):
    """POST multipart without the JSON Content-Type header that would break boundary.

    Passing Content-Type: None tells requests to drop the session-level header
    and let it be regenerated by the multipart encoder.
    """
    return session.post(url, files=files, headers={"Content-Type": None})

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")
assert BASE_URL, "REACT_APP_BACKEND_URL must be set"

ADMIN_EMAIL = "admin@factory.local"
ADMIN_PASS = "Admin@123"


# ---------------- Fixtures ----------------
@pytest.fixture(scope="session")
def admin_session():
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    r = s.post(f"{BASE_URL}/api/auth/login",
               json={"email": ADMIN_EMAIL, "password": ADMIN_PASS})
    assert r.status_code == 200, f"Admin login failed: {r.status_code} {r.text}"
    tok = r.json().get("access_token") or r.json().get("token")
    if tok:
        s.headers.update({"Authorization": f"Bearer {tok}"})
    return s


@pytest.fixture(scope="session")
def lines(admin_session):
    r = admin_session.get(f"{BASE_URL}/api/lines")
    assert r.status_code == 200
    return r.json()["data"]


# ---------------- Health / Auth ----------------
class TestHealth:
    def test_health(self):
        r = requests.get(f"{BASE_URL}/api/health")
        assert r.status_code == 200

    def test_admin_login(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/auth/me")
        assert r.status_code == 200
        assert r.json()["data"]["role"] == "admin"


# ---------------- Masters ----------------
class TestMasters:
    def test_departments(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/departments")
        assert r.status_code == 200
        data = r.json()["data"]
        codes = {d["code"] for d in data}
        assert "process" in codes and "packaging" in codes

    def test_lines_have_department(self, lines):
        assert len(lines) > 0
        # Each line must have a department to enable cascading
        for l in lines:
            assert l.get("department"), f"Line {l.get('code')} missing department"

    def test_lines_pc21_exists_in_both_departments(self, lines):
        pc21 = [l for l in lines if l.get("code") == "PC21"]
        depts = {l.get("department") for l in pc21}
        # Test expects PC21 to be ambiguous — exists in both process AND packaging
        assert "process" in depts and "packaging" in depts, (
            f"PC21 should exist in both process AND packaging depts for ambiguity test. Got: {depts}"
        )

    def test_machines_endpoint(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/machines")
        assert r.status_code == 200
        data = r.json()["data"]
        assert len(data) > 0


# ---------------- Shift Removal ----------------
class TestShiftRemoval:
    def test_breakdowns_no_shift_field(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/breakdowns?limit=20")
        assert r.status_code == 200
        for bd in r.json()["data"]:
            assert "shift" not in bd, f"Breakdown {bd.get('id')} still contains 'shift'"

    def test_work_orders_no_shift_field(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/work-orders?limit=20")
        assert r.status_code == 200
        for wo in r.json()["data"]:
            assert "shift" not in wo, f"WorkOrder {wo.get('id')} still contains 'shift'"

    def test_breakdowns_shift_filter_ignored(self, admin_session):
        # Even if a client sends shift, should not error (backwards compat)
        r = admin_session.get(f"{BASE_URL}/api/breakdowns?shift=A&limit=5")
        assert r.status_code in (200, 422)  # accept either ignored or explicitly rejected


# ---------------- Analytics: Dept KPI ----------------
class TestAnalyticsDept:
    def test_department_kpi_process(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/analytics/department/process/kpi")
        assert r.status_code == 200
        data = r.json()["data"]
        # Structure validation
        for k in ["department", "failures", "downtime_seconds",
                  "top_causes", "top_equipment", "monthly_trend"]:
            assert k in data, f"Missing key {k} in dept KPI"
        assert data["department"] == "process"
        assert isinstance(data["failures"], int)
        assert isinstance(data["top_equipment"], list)

    def test_department_kpi_packaging(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/analytics/department/packaging/kpi")
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["department"] == "packaging"

    def test_department_kpi_unknown(self, admin_session):
        # Unknown dept should return 200 with zeros (not error)
        r = admin_session.get(f"{BASE_URL}/api/analytics/department/nonexistent/kpi")
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["failures"] == 0


# ---------------- Bulk Runtime Import ----------------
class TestRuntimeBulkImport:
    def test_template_download(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/runtime/bulk-import/template")
        assert r.status_code == 200
        body = r.text
        # Must contain expected columns
        for col in ["line_code", "department", "date",
                    "calendar_hours", "dark_hours", "run_time_hours", "notes"]:
            assert col in body, f"Template missing column {col}"
        assert "text/csv" in r.headers.get("content-type", "")

    def test_dry_run_valid_csv(self, admin_session, lines):
        # Pick a line code that exists only once (not PC21)
        code_counts: dict = {}
        for l in lines:
            code_counts[l["code"]] = code_counts.get(l["code"], 0) + 1
        # Prefer a code that occurs only once
        unique_codes = [c for c, n in code_counts.items() if n == 1]
        assert unique_codes, "Need at least one uniquely-scoped line code for test"
        test_code = unique_codes[0]

        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            f"{test_code},,2026-02-10,24,2,20,TEST_dryrun\n"
            f"{test_code},,2026-02-11,24,1,22,TEST_dryrun\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200, r.text
        data = r.json()["data"]
        assert data["total_rows"] == 2
        assert data["valid_rows"] == 2
        assert data["error_count"] == 0

    def test_dry_run_ambiguous_line_code(self, admin_session):
        # PC21 exists in both departments — should raise ambiguity error
        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            "PC21,,2026-02-10,24,2,20,ok\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["error_count"] >= 1
        assert data["valid_rows"] == 0
        # Should surface ambiguity in error message
        err_text = " ".join(sum([e.get("errors", []) for e in data["errors"]], []))
        assert "multiple departments" in err_text.lower() or "ambiguous" in err_text.lower(), (
            f"Expected ambiguity error, got: {err_text}"
        )

    def test_dry_run_pc21_with_department_resolves(self, admin_session):
        # PC21 with explicit department should resolve fine
        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            "PC21,process,2026-02-12,24,2,20,ok\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["valid_rows"] == 1, f"Expected 1 valid row, got {data}"
        assert data["error_count"] == 0

    def test_dry_run_invalid_rows(self, admin_session):
        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            "BOGUS_CODE,,2026-02-10,24,2,20,unknown line\n"
            "PC21,process,not-a-date,24,2,20,bad date\n"
            "PC21,process,2026-02-13,10,0,15,run > cal\n"
            "PC21,process,2026-02-14,-1,0,10,negative cal\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["error_count"] >= 4, f"Expected >=4 errors, got {data['error_count']}: {data['errors']}"
        assert data["valid_rows"] == 0

    def test_dry_run_missing_columns(self, admin_session):
        # Missing dark_hours column → should 400
        csv_body = (
            "line_code,date,calendar_hours,run_time_hours\n"
            "PC21,2026-02-10,24,20\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 400

    def test_commit_inserts_and_updates(self, admin_session, lines):
        # Pick a unique line
        code_counts: dict = {}
        for l in lines:
            code_counts[l["code"]] = code_counts.get(l["code"], 0) + 1
        unique_codes = [c for c, n in code_counts.items() if n == 1]
        test_code = unique_codes[0]

        # First commit — insert
        csv_body_1 = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            f"{test_code},,2026-03-01,24,2,20,TEST_bulk_first\n"
            f"{test_code},,2026-03-02,24,3,19,TEST_bulk_first\n"
        )
        files = {"file": ("t.csv", io.BytesIO(csv_body_1.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/commit", files)
        assert r.status_code == 200, r.text
        data = r.json()["data"]
        total_new = data["inserted"] + data["updated"]
        assert total_new == 2
        # At least one insert on first commit (allow updates if re-running suite)
        assert data["skipped_errors"] == 0

        # Second commit with same lines + dates but new hours — should update
        csv_body_2 = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            f"{test_code},,2026-03-01,24,4,18,TEST_bulk_update\n"
            f"{test_code},,2026-03-02,24,5,17,TEST_bulk_update\n"
        )
        files = {"file": ("t.csv", io.BytesIO(csv_body_2.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/commit", files)
        assert r.status_code == 200
        data2 = r.json()["data"]
        assert data2["updated"] == 2, f"Expected 2 updates, got {data2}"
        assert data2["inserted"] == 0

        # Verify persistence via GET
        # Find line_id
        line_id = next(l["id"] for l in lines if l["code"] == test_code)
        gr = admin_session.get(f"{BASE_URL}/api/runtime?line_id={line_id}&date_from=2026-03-01&date_to=2026-03-02")
        assert gr.status_code == 200
        found = {r["date"]: r for r in gr.json()["data"]}
        assert "2026-03-01" in found
        assert found["2026-03-01"]["dark_hours"] == 4
        assert found["2026-03-01"]["run_time_hours"] == 18

    def test_commit_non_admin_denied(self):
        # Non-admin user cannot commit
        s = requests.Session()
        s.headers.update({"Content-Type": "application/json"})
        r = s.post(f"{BASE_URL}/api/auth/login",
                   json={"email": "op@factory.local", "password": "Op@123"})
        if r.status_code != 200:
            pytest.skip("Operator login not available")
        tok = r.json().get("access_token") or r.json().get("token")
        if tok:
            s.headers.update({"Authorization": f"Bearer {tok}"})

        csv_body = "line_code,date,calendar_hours,dark_hours,run_time_hours\nPC21,2026-04-01,24,0,20\n"
        files = {"file": ("t.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r2 = _multipart_post(s, f"{BASE_URL}/api/runtime/bulk-import/commit", files)
        assert r2.status_code in (401, 403), f"Non-admin should be denied, got {r2.status_code}"


# ---------------- Breakdowns filter by dept/line/machine ----------------
class TestBreakdownsFilter:
    def test_by_department(self, admin_session):
        r_all = admin_session.get(f"{BASE_URL}/api/breakdowns?limit=200")
        assert r_all.status_code == 200
        n_all = len(r_all.json()["data"])

        r_p = admin_session.get(f"{BASE_URL}/api/breakdowns?department=process&limit=200")
        assert r_p.status_code == 200
        n_p = len(r_p.json()["data"])

        r_k = admin_session.get(f"{BASE_URL}/api/breakdowns?department=packaging&limit=200")
        assert r_k.status_code == 200
        n_k = len(r_k.json()["data"])

        # sums should not exceed all (they're subsets)
        assert n_p <= n_all
        assert n_k <= n_all
