"""Backend regression tests for Factory CMMS Enterprise.

Focus of THIS iteration:
- Shift removal validation (no `shift` field in breakdowns/work_orders responses)
- Bulk runtime CSV import (dry-run, commit, template) — happy + edge cases
- Department cascading (dept -> lines scope), department KPI endpoint

Uses REACT_APP_BACKEND_URL from environment. Run:
    pytest /app/backend/tests/backend_test.py -v --junitxml=/app/test_reports/pytest/pytest_results.xml
"""
import io
import os
import pytest
import requests


def _multipart_post(session: requests.Session, url: str, files):
    """POST multipart without the JSON Content-Type header that would break boundary.

    Passing Content-Type: None tells requests to drop the session-level header
    and let it be regenerated by the multipart encoder.
    """
    return session.post(url, files=files, headers={"Content-Type": None})

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")
assert BASE_URL, "REACT_APP_BACKEND_URL must be set"

ADMIN_EMAIL = "admin@factory.local"
ADMIN_PASS = "Admin@123"


# ---------------- Fixtures ----------------
@pytest.fixture(scope="session")
def admin_session():
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    r = s.post(f"{BASE_URL}/api/auth/login",
               json={"email": ADMIN_EMAIL, "password": ADMIN_PASS})
    assert r.status_code == 200, f"Admin login failed: {r.status_code} {r.text}"
    tok = r.json().get("access_token") or r.json().get("token")
    if tok:
        s.headers.update({"Authorization": f"Bearer {tok}"})
    return s


@pytest.fixture(scope="session")
def lines(admin_session):
    r = admin_session.get(f"{BASE_URL}/api/lines")
    assert r.status_code == 200
    return r.json()["data"]


# ---------------- Health / Auth ----------------
class TestHealth:
    def test_health(self):
        r = requests.get(f"{BASE_URL}/api/health")
        assert r.status_code == 200

    def test_admin_login(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/auth/me")
        assert r.status_code == 200
        assert r.json()["data"]["role"] == "admin"


# ---------------- Masters ----------------
class TestMasters:
    def test_departments(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/departments")
        assert r.status_code == 200
        data = r.json()["data"]
        codes = {d["code"] for d in data}
        assert "process" in codes and "packaging" in codes

    def test_lines_have_department(self, lines):
        assert len(lines) > 0
        # Each line must have a department to enable cascading
        for ln in lines:
            assert ln.get("department"), f"Line {ln.get('code')} missing department"

    def test_lines_pc21_exists_in_both_departments(self, lines):
        pc21 = [ln for ln in lines if ln.get("code") == "PC21"]
        depts = {ln.get("department") for ln in pc21}
        # Test expects PC21 to be ambiguous — exists in both process AND packaging
        assert "process" in depts and "packaging" in depts, (
            f"PC21 should exist in both process AND packaging depts for ambiguity test. Got: {depts}"
        )

    def test_machines_endpoint(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/machines")
        assert r.status_code == 200
        data = r.json()["data"]
        assert len(data) > 0


# ---------------- Shift Removal ----------------
class TestShiftRemoval:
    def test_breakdowns_no_shift_field(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/breakdowns?limit=20")
        assert r.status_code == 200
        for bd in r.json()["data"]:
            assert "shift" not in bd, f"Breakdown {bd.get('id')} still contains 'shift'"

    def test_work_orders_no_shift_field(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/work-orders?limit=20")
        assert r.status_code == 200
        for wo in r.json()["data"]:
            assert "shift" not in wo, f"WorkOrder {wo.get('id')} still contains 'shift'"

    def test_breakdowns_shift_filter_ignored(self, admin_session):
        # Even if a client sends shift, should not error (backwards compat)
        r = admin_session.get(f"{BASE_URL}/api/breakdowns?shift=A&limit=5")
        assert r.status_code in (200, 422)  # accept either ignored or explicitly rejected


# ---------------- Analytics: Dept KPI ----------------
class TestAnalyticsDept:
    def test_department_kpi_process(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/analytics/department/process/kpi")
        assert r.status_code == 200
        data = r.json()["data"]
        # Structure validation
        for k in ["department", "failures", "downtime_seconds",
                  "top_causes", "top_equipment", "monthly_trend"]:
            assert k in data, f"Missing key {k} in dept KPI"
        assert data["department"] == "process"
        assert isinstance(data["failures"], int)
        assert isinstance(data["top_equipment"], list)

    def test_department_kpi_packaging(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/analytics/department/packaging/kpi")
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["department"] == "packaging"

    def test_department_kpi_unknown(self, admin_session):
        # Unknown dept should return 200 with zeros (not error)
        r = admin_session.get(f"{BASE_URL}/api/analytics/department/nonexistent/kpi")
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["failures"] == 0


# ---------------- Bulk Runtime Import ----------------
class TestRuntimeBulkImport:
    def test_template_download(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/runtime/bulk-import/template")
        assert r.status_code == 200
        body = r.text
        # Must contain expected columns
        for col in ["line_code", "department", "date",
                    "calendar_hours", "dark_hours", "run_time_hours", "notes"]:
            assert col in body, f"Template missing column {col}"
        assert "text/csv" in r.headers.get("content-type", "")

    def test_dry_run_valid_csv(self, admin_session, lines):
        # Pick a line code that exists only once (not PC21)
        code_counts: dict = {}
        for ln in lines:
            code_counts[ln["code"]] = code_counts.get(ln["code"], 0) + 1
        # Prefer a code that occurs only once
        unique_codes = [c for c, n in code_counts.items() if n == 1]
        assert unique_codes, "Need at least one uniquely-scoped line code for test"
        test_code = unique_codes[0]

        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            f"{test_code},,2026-02-10,24,2,20,TEST_dryrun\n"
            f"{test_code},,2026-02-11,24,1,22,TEST_dryrun\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200, r.text
        data = r.json()["data"]
        assert data["total_rows"] == 2
        assert data["valid_rows"] == 2
        assert data["error_count"] == 0

    def test_dry_run_ambiguous_line_code(self, admin_session):
        # PC21 exists in both departments — should raise ambiguity error
        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            "PC21,,2026-02-10,24,2,20,ok\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["error_count"] >= 1
        assert data["valid_rows"] == 0
        # Should surface ambiguity in error message
        err_text = " ".join(sum([e.get("errors", []) for e in data["errors"]], []))
        assert "multiple departments" in err_text.lower() or "ambiguous" in err_text.lower(), (
            f"Expected ambiguity error, got: {err_text}"
        )

    def test_dry_run_pc21_with_department_resolves(self, admin_session):
        # PC21 with explicit department should resolve fine
        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            "PC21,process,2026-02-12,24,2,20,ok\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["valid_rows"] == 1, f"Expected 1 valid row, got {data}"
        assert data["error_count"] == 0

    def test_dry_run_invalid_rows(self, admin_session):
        csv_body = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            "BOGUS_CODE,,2026-02-10,24,2,20,unknown line\n"
            "PC21,process,not-a-date,24,2,20,bad date\n"
            "PC21,process,2026-02-13,10,0,15,run > cal\n"
            "PC21,process,2026-02-14,-1,0,10,negative cal\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 200
        data = r.json()["data"]
        assert data["error_count"] >= 4, f"Expected >=4 errors, got {data['error_count']}: {data['errors']}"
        assert data["valid_rows"] == 0

    def test_dry_run_missing_columns(self, admin_session):
        # Missing dark_hours column → should 400
        csv_body = (
            "line_code,date,calendar_hours,run_time_hours\n"
            "PC21,2026-02-10,24,20\n"
        )
        files = {"file": ("test.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/dry-run", files)
        assert r.status_code == 400

    def test_commit_inserts_and_updates(self, admin_session, lines):
        # Pick a unique line
        code_counts: dict = {}
        for ln in lines:
            code_counts[ln["code"]] = code_counts.get(ln["code"], 0) + 1
        unique_codes = [c for c, n in code_counts.items() if n == 1]
        test_code = unique_codes[0]

        # First commit — insert
        csv_body_1 = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            f"{test_code},,2026-03-01,24,2,20,TEST_bulk_first\n"
            f"{test_code},,2026-03-02,24,3,19,TEST_bulk_first\n"
        )
        files = {"file": ("t.csv", io.BytesIO(csv_body_1.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/commit", files)
        assert r.status_code == 200, r.text
        data = r.json()["data"]
        total_new = data["inserted"] + data["updated"]
        assert total_new == 2
        # At least one insert on first commit (allow updates if re-running suite)
        assert data["skipped_errors"] == 0

        # Second commit with same lines + dates but new hours — should update
        csv_body_2 = (
            "line_code,department,date,calendar_hours,dark_hours,run_time_hours,notes\n"
            f"{test_code},,2026-03-01,24,4,18,TEST_bulk_update\n"
            f"{test_code},,2026-03-02,24,5,17,TEST_bulk_update\n"
        )
        files = {"file": ("t.csv", io.BytesIO(csv_body_2.encode()), "text/csv")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/runtime/bulk-import/commit", files)
        assert r.status_code == 200
        data2 = r.json()["data"]
        assert data2["updated"] == 2, f"Expected 2 updates, got {data2}"
        assert data2["inserted"] == 0

        # Verify persistence via GET
        # Find line_id
        line_id = next(ln["id"] for ln in lines if ln["code"] == test_code)
        gr = admin_session.get(f"{BASE_URL}/api/runtime?line_id={line_id}&date_from=2026-03-01&date_to=2026-03-02")
        assert gr.status_code == 200
        found = {r["date"]: r for r in gr.json()["data"]}
        assert "2026-03-01" in found
        assert found["2026-03-01"]["dark_hours"] == 4
        assert found["2026-03-01"]["run_time_hours"] == 18

    def test_commit_non_admin_denied(self):
        # Non-admin user cannot commit
        s = requests.Session()
        s.headers.update({"Content-Type": "application/json"})
        r = s.post(f"{BASE_URL}/api/auth/login",
                   json={"email": "op@factory.local", "password": "Op@123"})
        if r.status_code != 200:
            pytest.skip("Operator login not available")
        tok = r.json().get("access_token") or r.json().get("token")
        if tok:
            s.headers.update({"Authorization": f"Bearer {tok}"})

        csv_body = "line_code,date,calendar_hours,dark_hours,run_time_hours\nPC21,2026-04-01,24,0,20\n"
        files = {"file": ("t.csv", io.BytesIO(csv_body.encode()), "text/csv")}
        r2 = _multipart_post(s, f"{BASE_URL}/api/runtime/bulk-import/commit", files)
        assert r2.status_code in (401, 403), f"Non-admin should be denied, got {r2.status_code}"


# ---------------- Breakdowns filter by dept/line/machine ----------------
class TestBreakdownsFilter:
    def test_by_department(self, admin_session):
        r_all = admin_session.get(f"{BASE_URL}/api/breakdowns?limit=200")
        assert r_all.status_code == 200
        n_all = len(r_all.json()["data"])

        r_p = admin_session.get(f"{BASE_URL}/api/breakdowns?department=process&limit=200")
        assert r_p.status_code == 200
        n_p = len(r_p.json()["data"])

        r_k = admin_session.get(f"{BASE_URL}/api/breakdowns?department=packaging&limit=200")
        assert r_k.status_code == 200
        n_k = len(r_k.json()["data"])

        # sums should not exceed all (they're subsets)
        assert n_p <= n_all
        assert n_k <= n_all



# =====================================================================
# ITERATION 4 — new coverage
#   * Personnel analytics
#   * Branding GET/PUT + logo upload/download/delete
#   * Work-order PATCH (priority + timestamps, role checks)
#   * Admin data-ops (data-summary, seed-demo, wipe-transactional round-trip)
# =====================================================================

TECH_EMAIL = "tech@factory.local"
TECH_PASS = "Tech@123"
OP_EMAIL = "op@factory.local"
OP_PASS = "Op@123"


def _login_session(email: str, password: str) -> requests.Session:
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    r = s.post(f"{BASE_URL}/api/auth/login", json={"email": email, "password": password})
    if r.status_code != 200:
        return None
    tok = r.json().get("access_token") or r.json().get("token")
    if tok:
        s.headers.update({"Authorization": f"Bearer {tok}"})
    return s


@pytest.fixture(scope="session")
def tech_session():
    s = _login_session(TECH_EMAIL, TECH_PASS)
    if s is None:
        pytest.skip("Technician login failed")
    return s


@pytest.fixture(scope="session")
def op_session():
    s = _login_session(OP_EMAIL, OP_PASS)
    if s is None:
        pytest.skip("Operator login failed")
    return s


# ---------------- Personnel Analytics ----------------
class TestPersonnelAnalytics:
    def test_requires_auth(self):
        r = requests.get(f"{BASE_URL}/api/analytics/personnel")
        assert r.status_code in (401, 403)

    def test_shape(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/analytics/personnel")
        assert r.status_code == 200, r.text
        data = r.json()["data"]
        for k in ("reporters", "technicians", "top"):
            assert k in data
        assert isinstance(data["reporters"], list)
        assert isinstance(data["technicians"], list)
        top = data["top"]
        for k in ("most_active_reporter", "most_active_technician",
                  "fastest_technician", "slowest_technician"):
            assert k in top

        for r_row in data["reporters"]:
            assert "name" in r_row and "breakdowns_reported" in r_row
        for t in data["technicians"]:
            for k in ("user_id", "name", "work_orders_completed",
                      "total_repair_seconds", "avg_repair_seconds", "avg_response_seconds"):
                assert k in t, f"technician row missing {k}: {t}"

    def test_filter_reduces_rows(self, admin_session):
        r_all = admin_session.get(f"{BASE_URL}/api/analytics/personnel").json()["data"]
        # from/to way in the future should yield empty subsets
        r_fut = admin_session.get(
            f"{BASE_URL}/api/analytics/personnel?from=2099-01-01T00:00:00Z&to=2099-12-31T00:00:00Z"
        ).json()["data"]
        assert len(r_fut["reporters"]) <= len(r_all["reporters"])
        assert len(r_fut["technicians"]) <= len(r_all["technicians"])

        r_dept = admin_session.get(
            f"{BASE_URL}/api/analytics/personnel?department=process"
        ).json()["data"]
        assert len(r_dept["technicians"]) <= len(r_all["technicians"])


# ---------------- Branding ----------------
class TestBranding:
    def test_get_branding_public(self):
        r = requests.get(f"{BASE_URL}/api/settings/branding")
        assert r.status_code == 200
        data = r.json()["data"]
        for k in ("company_name", "primary_color", "has_logo", "logo_ext", "logo_updated_at"):
            assert k in data

    def test_put_requires_admin(self, op_session):
        # form-encoded PUT as operator → 403
        r = op_session.put(
            f"{BASE_URL}/api/settings/branding",
            data={"company_name": "HACK"},
            headers={"Content-Type": None},
        )
        assert r.status_code in (401, 403), r.text

    def test_put_updates_name_and_color(self, admin_session):
        original = admin_session.get(f"{BASE_URL}/api/settings/branding").json()["data"]
        new_name = "Factory CMMS TEST"
        new_color = "#22d3ee"
        r = admin_session.put(
            f"{BASE_URL}/api/settings/branding",
            data={"company_name": new_name, "primary_color": new_color},
            headers={"Content-Type": None},
        )
        assert r.status_code == 200, r.text
        got = admin_session.get(f"{BASE_URL}/api/settings/branding").json()["data"]
        assert got["company_name"] == new_name
        assert got["primary_color"].lower() == new_color.lower()
        # restore
        admin_session.put(
            f"{BASE_URL}/api/settings/branding",
            data={
                "company_name": original.get("company_name") or "Factory CMMS",
                "primary_color": original.get("primary_color") or "#22d3ee",
            },
            headers={"Content-Type": None},
        )

    def test_put_invalid_color(self, admin_session):
        r = admin_session.put(
            f"{BASE_URL}/api/settings/branding",
            data={"primary_color": "not-a-hex"},
            headers={"Content-Type": None},
        )
        assert r.status_code == 400

    def _tiny_png_bytes(self):
        # 1x1 red PNG (pure bytes; no PIL required)
        return bytes.fromhex(
            "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4"
            "89000000164944415478da62f8cfc0f09f81010c0c02000000ffff0300060005"
            "032c19ba470000000049454e44ae426082"
        )

    def test_logo_upload_download_delete(self, admin_session):
        png = self._tiny_png_bytes()
        files = {"file": ("logo.png", io.BytesIO(png), "image/png")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/settings/branding/logo", files)
        assert r.status_code == 200, r.text
        data = r.json()["data"]
        assert data["logo_ext"] == ".png"
        assert data["bytes"] == len(png)

        # verify GET branding reflects has_logo=true
        meta = admin_session.get(f"{BASE_URL}/api/settings/branding").json()["data"]
        assert meta["has_logo"] is True
        assert meta["logo_ext"] == ".png"

        # GET logo file (public)
        rf = requests.get(f"{BASE_URL}/api/settings/branding/logo")
        assert rf.status_code == 200
        assert rf.headers.get("content-type", "").startswith("image/png")
        assert rf.content == png

        # DELETE
        rd = admin_session.delete(f"{BASE_URL}/api/settings/branding/logo")
        assert rd.status_code == 200
        meta2 = admin_session.get(f"{BASE_URL}/api/settings/branding").json()["data"]
        assert meta2["has_logo"] is False
        # GET the file now 404
        rf2 = requests.get(f"{BASE_URL}/api/settings/branding/logo")
        assert rf2.status_code == 404

    def test_logo_upload_rejects_bad_ext(self, admin_session):
        files = {"file": ("logo.gif", io.BytesIO(b"gifdata"), "image/gif")}
        r = _multipart_post(admin_session, f"{BASE_URL}/api/settings/branding/logo", files)
        assert r.status_code == 400

    def test_logo_upload_requires_admin(self, op_session):
        files = {"file": ("logo.png", io.BytesIO(b"\x89PNGxxx"), "image/png")}
        r = _multipart_post(op_session, f"{BASE_URL}/api/settings/branding/logo", files)
        assert r.status_code in (401, 403)


# ---------------- WorkOrder PATCH ----------------
class TestWorkOrderPatch:
    def _pick_wo(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/work-orders?limit=50")
        assert r.status_code == 200
        # prefer closed WO to avoid disturbing lifecycle
        wos = r.json()["data"]
        closed = [w for w in wos if w.get("status") == "closed"]
        return (closed[0] if closed else wos[0]) if wos else None

    def test_patch_priority_admin(self, admin_session):
        wo = self._pick_wo(admin_session)
        if not wo:
            pytest.skip("No work orders available")
        orig = wo.get("priority") or "p3"
        r = admin_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}",
                                 json={"priority": "p1"})
        assert r.status_code == 200, r.text
        assert r.json()["data"]["priority"] == "p1"
        # revert
        admin_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}",
                             json={"priority": orig})

    def test_patch_invalid_priority(self, admin_session):
        wo = self._pick_wo(admin_session)
        if not wo:
            pytest.skip("No work orders")
        r = admin_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}",
                                 json={"priority": "urgent"})
        assert r.status_code == 400
        body = r.json()
        detail = body.get("detail") or {}
        if isinstance(detail, dict):
            assert detail.get("code") == "WO_INVALID_PRIORITY"

    def test_patch_technician_can_edit(self, admin_session, tech_session):
        wo = self._pick_wo(admin_session)
        if not wo:
            pytest.skip("No work orders")
        r = tech_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}",
                                json={"priority": "p2"})
        assert r.status_code == 200, r.text
        assert r.json()["data"]["priority"] == "p2"

    def test_patch_operator_denied(self, admin_session, op_session):
        wo = self._pick_wo(admin_session)
        if not wo:
            pytest.skip("No work orders")
        r = op_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}",
                              json={"priority": "p3"})
        assert r.status_code in (401, 403)

    def test_patch_timestamps_and_derived(self, admin_session):
        wo = self._pick_wo(admin_session)
        if not wo:
            pytest.skip("No work orders")
        assigned = "2026-01-01T08:00:00+00:00"
        started = "2026-01-01T08:30:00+00:00"
        completed = "2026-01-01T09:15:00+00:00"
        closed = "2026-01-01T09:30:00+00:00"
        r = admin_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}", json={
            "assigned_at": assigned,
            "repair_started_at": started,
            "repair_completed_at": completed,
            "closed_at": closed,
        })
        assert r.status_code == 200, r.text
        wo2 = r.json()["data"]
        # Timestamps saved
        assert wo2["assigned_at"] == assigned
        assert wo2["repair_started_at"] == started
        assert wo2["repair_completed_at"] == completed
        assert wo2["closed_at"] == closed
        # Derived
        assert wo2.get("response_time_seconds") == 30 * 60
        assert wo2.get("repair_time_seconds") == 45 * 60
        assert wo2.get("close_time_seconds") == 90 * 60

    def test_patch_invalid_timestamp(self, admin_session):
        wo = self._pick_wo(admin_session)
        if not wo:
            pytest.skip("No work orders")
        r = admin_session.patch(f"{BASE_URL}/api/work-orders/{wo['id']}",
                                 json={"assigned_at": "not-a-date"})
        assert r.status_code == 400
        detail = r.json().get("detail") or {}
        if isinstance(detail, dict):
            assert detail.get("code") == "WO_INVALID_TIMESTAMP"


# ---------------- Admin Data Ops ----------------
class TestAdminDataOps:
    def test_data_summary_admin(self, admin_session):
        r = admin_session.get(f"{BASE_URL}/api/admin/data-summary")
        assert r.status_code == 200
        data = r.json()["data"]
        for c in ("users", "machines", "production_lines",
                  "breakdowns", "work_orders"):
            assert c in data
            assert isinstance(data[c], int)

    def test_data_summary_non_admin(self, op_session):
        r = op_session.get(f"{BASE_URL}/api/admin/data-summary")
        assert r.status_code in (401, 403)

    def test_seed_demo_idempotent(self, admin_session):
        r = admin_session.post(f"{BASE_URL}/api/admin/seed-demo")
        assert r.status_code == 200, r.text
        # baseline machine count
        s1 = admin_session.get(f"{BASE_URL}/api/admin/data-summary").json()["data"]
        m1 = s1["machines"]
        # run again — should not multiply
        r2 = admin_session.post(f"{BASE_URL}/api/admin/seed-demo")
        assert r2.status_code == 200
        s2 = admin_session.get(f"{BASE_URL}/api/admin/data-summary").json()["data"]
        assert s2["machines"] == m1, "seed-demo not idempotent: machines duplicated"

    def test_wipe_endpoints_reachable_non_admin_403(self, op_session):
        r = op_session.post(f"{BASE_URL}/api/admin/wipe-transactional")
        assert r.status_code in (401, 403)
        r2 = op_session.post(f"{BASE_URL}/api/admin/wipe-demo")
        assert r2.status_code in (401, 403)

    # NOTE: We intentionally do NOT run wipe-transactional / wipe-demo against
    # the live preview DB (destructive). Existence + auth guarding is validated
    # by the two negative tests above and the seed_demo round-trip.
